# --------------- Main ---------------

library: library.db
directory: ~/Music
statefile: state.pickle

# --------------- Plugins ---------------

plugins: []
pluginpath: []

# --------------- Import ---------------

clutter: ["Thumbs.DB", ".DS_Store"]
ignore: [".*", "*~", "System Volume Information", "lost+found"]
ignore_hidden: yes

import:
    # common options
    write: yes
    copy: yes
    move: no
    timid: no
    quiet: no
    log:
    # other options
    default_action: apply
    languages: []
    quiet_fallback: skip
    none_rec_action: ask
    # rare options
    link: no
    hardlink: no
    reflink: no
    delete: no
    resume: ask
    incremental: no
    incremental_skip_later: no
    from_scratch: no
    autotag: yes
    singletons: no
    detail: no
    flat: no
    group_albums: no
    pretend: false
    search_ids: []
    duplicate_keys:
        album: albumartist album
        item: artist title
    duplicate_action: ask
    duplicate_verbose_prompt: no
    bell: no
    set_fields: {}
    ignored_alias_types: []
    singleton_album_disambig: yes

# --------------- Paths ---------------

path_sep_replace: _
drive_sep_replace: _
asciify_paths: false
art_filename: cover
max_filename_length: 0
replace:
    # Replace bad characters with _
    # prohibited in many filesystem paths
    '[<>:\?\*\|]': _
    # double quotation mark "
    '\"': _
    # path separators: \ or /
    '[\\/]': _
    # starting and closing periods
    '^\.': _
    '\.$': _
    # control characters
    '[\x00-\x1f]': _
    # dash at the start of a filename (causes command line ambiguity)
    '^-': _
    # Replace bad characters with nothing
    # starting and closing whitespace
    '\s+$': ''
    '^\s+': ''

aunique:
    keys: albumartist album
    disambiguators: albumtype year label catalognum albumdisambig releasegroupdisambig
    bracket: '[]'

sunique:
    keys: artist title
    disambiguators: year trackdisambig
    bracket: '[]'

# --------------- Tagging ---------------

per_disc_numbering: no
original_date: no
artist_credit: no
id3v23: no
va_name: "Various Artists"
paths:
    default: $albumartist/$album%aunique{}/$track $title
    singleton: Non-Album/$artist/$title
    comp: Compilations/$album%aunique{}/$track $title

# --------------- Performance ---------------

threaded: yes
timeout: 5.0

# --------------- UI ---------------

verbose: 0
terminal_encoding:

ui:
    terminal_width: 80
    length_diff_thresh: 10.0
    color: yes
    colors:
        text_success: ['bold', 'green']
        text_warning: ['bold', 'yellow']
        text_error: ['bold', 'red']
        text_highlight: ['bold', 'red']
        text_highlight_minor: ['white']
        action_default: ['bold', 'cyan']
        action: ['bold', 'cyan']
        # New Colors
        text: ['normal']
        text_faint: ['faint']
        import_path: ['bold', 'blue']
        import_path_items: ['bold', 'blue']
        added:   ['green']
        removed: ['red']
        changed: ['yellow']
        added_highlight:   ['bold', 'green']
        removed_highlight: ['bold', 'red']
        changed_highlight: ['bold', 'yellow']
        text_diff_added:   ['bold', 'red']
        text_diff_removed: ['bold', 'red']
        text_diff_changed: ['bold', 'red']
        action_description: ['white']
    import:
        indentation:
            match_header: 2
            match_details: 2
            match_tracklist: 5
        layout: column

# --------------- Search ---------------

format_item: $artist - $album - $title
format_album: $albumartist - $album
time_format: '%Y-%m-%d %H:%M:%S'
format_raw_length: no

sort_album: albumartist+ album+
sort_item: artist+ album+ disc+ track+
sort_case_insensitive: yes

# --------------- Autotagger ---------------

overwrite_null:
  album: []
  track: []
musicbrainz:
    enabled: yes
    host: musicbrainz.org
    https: no
    ratelimit: 1
    ratelimit_interval: 1.0
    searchlimit: 5
    extra_tags: []
    genres: no
    external_ids:
        discogs: no
        bandcamp: no
        spotify: no
        deezer: no
        beatport: no
        tidal: no

match:
    strong_rec_thresh: 0.04
    medium_rec_thresh: 0.25
    rec_gap_thresh: 0.25
    max_rec:
        missing_tracks: medium
        unmatched_tracks: medium
    distance_weights:
        source: 2.0
        artist: 3.0
        album: 3.0
        media: 1.0
        mediums: 1.0
        year: 1.0
        country: 0.5
        label: 0.5
        catalognum: 0.5
        albumdisambig: 0.5
        album_id: 5.0
        tracks: 2.0
        missing_tracks: 0.9
        unmatched_tracks: 0.6
        track_title: 3.0
        track_artist: 2.0
        track_index: 1.0
        track_length: 2.0
        track_id: 5.0
        medium: 1.0
    preferred:
        countries: []
        media: []
        original_year: no
    ignored: []
    required: []
    ignored_media: []
    ignore_data_tracks: yes
    ignore_video_tracks: yes
    track_length_grace: 10
    track_length_max: 30
    album_disambig_fields: data_source media year country label catalognum albumdisambig
    singleton_disambig_fields: data_source index track_alt album
